stages:
  - build

build_ios:
  stage: build
  tags:
    - macos  # Критически важно: этот тег указывает, что нужен сервер с macOS
  script:
    - flutter doctor
    - flutter pub get
    # Сборка без подписи (если нужно просто проверить, что код компилируется)
    - flutter build ios --release --no-codesign
    # Если нужны архивы для стора, обычно используют fastlane
  artifacts:
    paths:
      - build/ios/iphoneos/Runner.app
    expire_in: 1 week